POST http://localhost:3000/api/users?i=9
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmNTkwYTZlNzQ0ZGM3MjI0ZjAyZDliIiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5MzgzMTU1NCwiZXhwIjoxNjk0Mjc0MzU0fQ.RSyVRdSURJIzhD1UvUnW5k5ls-K8u7B-xfJ9xxkSsaY
Content-Type: application/json

{   
    "first_name":"Iroda",
    "last_name":"rere",
    "age":20,
    "username":"iroda0103",
    "role":"admin",
    "password":"1234"
}

###
GET http://localhost:3000/api/users?page[limit]=13&page[offset]=0&sort[by]=age&sort[order]=desc

###
GET http://localhost:3000/api/users/64f871e6f3fd6493b2acab99
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmYTAyNTNkY2E1NTI2MmYyZTZjYjJjIiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NDEwNjIxNiwiZXhwIjoxNjk0NTQ5MDE2fQ.BhcjptTP_VFMe8o7wJDlzDKU96zQRHH4I5bZ7lkOSw4

###
DELETE http://localhost:3000/api/users/64f33f968d57ee76ef9ab2f1

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
     "username":"iroda0103",
    "password":"1234"
}

###
GET http://localhost:3000/api/users/me
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmODcyMDNmM2ZkNjQ5M2IyYWNhYjljIiwicm9sZSI6ImVtcGxveWVlIn0sImlhdCI6MTY5NDAwMzc2NywiZXhwIjoxNjk0NDQ2NTY3fQ.9cc-P03YLWlxL8d_bGv6HpKDEwwUhSnXQVMAQvNL2mU

###
PATCH http://localhost:3000/api/users/64fa0253dca55262f2e6cb2c
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmNTkwYTZlNzQ0ZGM3MjI0ZjAyZDliIiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5MzgzMTU1NCwiZXhwIjoxNjk0Mjc0MzU0fQ.RSyVRdSURJIzhD1UvUnW5k5ls-K8u7B-xfJ9xxkSsaY
Content-Type: application/json

{
    "first_name":"Isdsdd"
}

###
PATCH http://localhost:3000/api/users/me
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmNWNlMmYzNTU2YjdlNjIyZDc5YmIwIiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5Mzg4ODYwMiwiZXhwIjoxNjk0MzMxNDAyfQ.YV-LfIWflhqE94RfwfqnoyYfVLXQh2oZDnTeDgHoHGs
Content-Type: application/json

{
    "first_name":"Iroda0103"
}

